name: transdeepseg
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - cudnn
  - cudatoolkit=11.2
  - cvxopt
  - cython
  - graphviz
  - ipython
  - mahotas
  - matplotlib
  - numpy
  - opencv-python
  - pandas
  - pillow
  - pydot
  - pyqt
  - pytest
  - python=3.11
  - python-graphviz
  - pytorch=1.6
  - scikit-image
  - scipy
  - tensorboardx
  - imageio
  - seaborn
  - tifffile
  - torchvision
  - pip 
  - imageio 
  - scikit-learn
  - imagecodecs
  - pandas
  - scipy

 

 